config/routes.rb
Valeur::Application.routes.draw do
  
  devise_for :utilisateurs

  resources :strategies, only: [:show, :edit, :update]

  resources :rentabilites, only: [:show]

  resources :directs, only: [:show, :edit, :update]

  resources :indirects, only: [:show, :edit, :update]

  resources :fonctions, only: [:show, :edit, :update]

  resources :gains, only: [:show, :edit, :update]

#  resources :detail, only: [:show]

  resources :parametrages


  resources :projets do
    resources :etudes
  end

  # map '/' to be a redirect to '/projets'

match "/" => redirect("/projets")
match '/aide_projets', :to => redirect('/aide_projets.html')

end

app/models/projet.rb
# encoding: utf-8
require 'coherence_projet'

class Resume
  include Mongoid::Document
  field :etude_id, type: Integer
  field :date, type: Date
  field :cout, type: Float
  field :duree, type: Float
  field :stade, type: Symbol
  field :note, type: Float
  embedded_in :projet
end

class Projet

  @@wf_etats = {:a_l_etude => [:soumis, :abandonne], :soumis => [:accepte, :refuse], :accepte => [:en_cours, :abandonne], \
    :en_cours => [:arrete, :termine], :arrete => [], :termine => [], :abandonne => [], :refuse => [:a_l_etude, :abandonne]}

  def self._supp
    [:abandonne]
  end

  def self._modif
    [:a_l_etude,:soumis,:accepte,:en_cours,:refuse]
  end

  def self._modif_date
    [:a_l_etude,:soumis,:accepte,:refuse]
  end

  def self.liste_ministeres
    ['Intermin','Aff.Etrangères','Agriculture','Culture','Défense','Ecologie','Finances','Intérieur','Sociaux','Serv. PM']
  end

  def self.liste_quotations
    [nil,0,1,2,3,4,5]
  end

  def liste_etats
    projet_base = Projet.where(_id: self._id).count
    if projet_base == 0
      return [:a_l_edude]
    else
      etat_base = Projet.find(self._id).etat
      if etat_base == :accepte && self.resumes == []
        liste = [:accepte,:abandonne]
      else
        liste = [etat_base]
        @@wf_etats[etat_base].each do |opt| liste <<= opt end
      end
      return liste
    end
  end

  def calcul_derives
    if self.resumes.size < 2 || (self.resumes.size == 2 && self.resumes[0].stade == :avant_projet) then
      self.derive_cout, self.derive_duree = nil, nil
      return self
    end
    base = self.resumes.select{ |resume| resume.stade != :avant_projet }.first
    self.derive_cout = ((self.resumes[-1].cout / base.cout) - 1 ) * 100.round
    self.derive_duree = ((self.resumes[-1].duree / base.duree) - 1 ) * 100.round
    return self
  end

  include Mongoid::Document
  include Mongoid::MultiParameterAttributes
  validates_with(CoherenceProjet)
  field :_id, type:Integer, default: ->{ if Projet.count == 0 then 1 else Projet.last._id + 1 end }
  field :code, type: String
  validates :code, :presence => {:message => "obligatoire"}
  validates :code, :uniqueness => {:message => "doit être unique"}
  field :nom, type: String
  validates :nom, :presence => {:message => "obligatoire"}
  field :ministere, type: String
  validates :ministere, :presence => {:message => "obligatoire"}
  field :public, type: Boolean, default: true
  validates :public, :presence => {:message => "obligatoire"}
  field :etat, type: Symbol, default: :a_l_etude
  validates :etat, :presence => {:message => "obligatoire"}
  validates :etat, :inclusion => { :in => [:a_l_etude,:soumis,:accepte,:en_cours,:termine,:arrete,:abandonne,:refuse],
    :message => "%{value} invalide" }
  field :description, type: String
  validates :description, :presence => {:message => "obligatoire"}
  field :entites_concernees, type: String
  validates :entites_concernees, :presence => {:message => "à préciser"}
  field :date_debut, type: Date
  validates :date_debut, :presence => {:message => "obligatoire pour un projet lancé",
	 :if => "[:en_cours,:arrete,:termine].include?(self.etat)" }
  field :derive_cout, type:Integer
  field :derive_duree, type:Integer
  field :quotation_disic, type:Integer
  validates :quotation_disic, :inclusion => { :in => [nil,0,1,2,3,4,5],
    :message => "%{value} invalide" }
  embeds_many :resumes
  has_many :etudes

end

app/controllers/projets_controller.rb
# encoding: utf-8

class ProjetsController < ApplicationController
  # GET /projets
  # GET /projets.json
  def index
    @projets = Projet.all.sort(_id: -1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projets }
    end
  end

  # GET /projets/1
  # GET /projets/1.json
  def show
    @projet = Projet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @projet }
    end
  end

  # GET /projets/new
  # GET /projets/new.json
  def new
    @projet = Projet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @projet }
    end
  end

  # GET /projets/1/edit
  def edit
    @projet = Projet.find(params[:id])
  end

  # POST /projets
  # POST /projets.json
  def create
    @projet = Projet.new(params[:projet])

    respond_to do |format|
      if @projet.save
        format.html { redirect_to @projet, notice: 'Le projet a été créé.' }
        format.json { render json: @projet, status: :created, location: @projet }
      else
        format.html { render action: "new" }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projets/1
  # PUT /projets/1.json
  def update
    @projet = Projet.find(params[:id])

    respond_to do |format|
      if @projet.update_attributes(params[:projet])
        format.html { redirect_to @projet, notice: 'Le projet a bien été mis à jour.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projets/1
  # DELETE /projets/1.json
  def destroy
    @projet = Projet.find(params[:id])
    @projet.destroy

    respond_to do |format|
      format.html { redirect_to projets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/projets/_form.html.haml
= form_for @projet do |f|
  - if @projet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@projet.errors.count, "erreurs")} : ce projet n'a pas pu être enregistré"
      %ul
        - @projet.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :code, 'Code'
    = f.text_field :code,:disabled => !(Projet._modif.include?(@projet.etat))
  .field
    = f.label :nom, 'Nom'
    = f.text_field :nom,:disabled => !(Projet._modif.include?(@projet.etat))
  .field
    = f.label :ministere, 'Ministères'
    = f.select :ministere, Projet.liste_ministeres,:disabled => if Projet._modif.include?(@projet.etat) then [] else Projet.liste_ministeres end
  .field
    = f.label :public, 'Public'
    = f.check_box :public,:disabled => !(Projet._modif.include?(@projet.etat))
  .field
    = f.label :description, 'Description'
    = f.text_field :description,:disabled => !(Projet._modif.include?(@projet.etat))
  .field
    = f.label :entites_concernees, 'Entités concernées'
    = f.text_field :entites_concernees,:disabled => !(Projet._modif.include?(@projet.etat))
  .field
    = f.label :date_debut, 'Date début'
    = f.date_select :date_debut, :use_month_numbers => true, :order => [:year, :month, :day],:disabled => !(Projet._modif_date.include?(@projet.etat))
  - if params["action"] != "new" then
    .field
      = f.label :etat, 'Etat'
      = f.select :etat, @projet.liste_etats,:disabled => if Projet._modif.include?(@projet.etat) then [] else @projet.liste_etats end
    .field
      = f.label :quotation_disic, 'Quotation'
      = f.select :quotation_disic, Projet.liste_quotations,:disabled => !(Projet._modif.include?(@projet.etat))
 
  .actions
    = f.submit 'Enregistrer'

app/views/projets/edit.html.haml
%h2 Modification du projet #{@projet.nom}

= render 'form'

= link_to 'Détail', @projet
\|
= link_to 'Retour à la liste', projets_path

app/views/projets/index.html.haml
%h2 Liste des projets de l'Etat

- if not @projets.empty? then

  %table#projets
    %tr
      %th Id
      %th Code
      %th Nom
      %th Ministère
      %th Public
      %th Etat
      %th Date début
      %th Montant
      %th Durée
      %th Delta coût
      %th Delta durée
      %th Quotation
      %th.rien
      %th.rien
      %th.rien

    - @projets.each do |projet|
      %tr
        %td.droit= projet._id
        %td= projet.code
        %td= projet.nom
        %td= projet.ministere
        %td.centre= "#{if projet.public then "Oui" else "Non" end}"
        %td= projet.etat.capitalize
        %td.centre= projet.date_debut
        %td.droit= number_with_precision(projet.resumes[-1].cout, options = {delimiter: " ", precision: 0}) if projet.resumes[-1]
        %td.droit= number_with_precision(projet.resumes[-1].duree, options = {precision: 1}) if projet.resumes[-1]
        %td.droit= number_to_percentage(projet.derive_cout, options = {precision: 0}) if projet.resumes[-1]
        %td.droit= number_to_percentage(projet.derive_duree, options = {precision: 0}) if projet.resumes[-1]
        %td.droit= projet.quotation_disic
        %td= link_to 'Détail', projet
        %td= link_to 'Etudes', projet_etudes_path(projet)
        %td= if Projet._modif.include?(projet.etat) then link_to 'Modif', edit_projet_path(projet) end
        %td= if Projet._supp.include?(projet.etat) then link_to 'Supp', projet, confirm: 'Poursuivre la suppression définitive ?', method: :delete end

%br

= link_to 'Nouveau projet', new_projet_path

app/views/projets/new.html.haml
%h2 Nouveau projet

= render 'form'

= link_to 'Retour à la liste', projets_path

app/views/projets/show.html.haml
%h2 Détail du projet #{@projet.nom}

%p#notice= notice

%table
  %tr
    %th
    %th
  %tr
    %td.bold Id
    %td= @projet._id
  %tr
    %td.bold Code
    %td= @projet.code
  %tr
    %td.bold Nom
    %td= @projet.nom
  %tr
    %td.bold Ministère
    %td= @projet.ministere
  %tr
    %td.bold Public
    %td= if @projet.public then "Oui" else "Non" end
  %tr
    %td.bold Description
    %td= @projet.description
  %tr
    %td.bold Entités concernées
    %td= @projet.entites_concernees
  %tr
    %td.bold Date début
    %td= @projet.date_debut
  %tr
    %td.bold Etat
    %td= @projet.etat
  %tr
    %td.bold Quotation DISIC
    %td= @projet.quotation_disic
  %tr
    %td.bold Coût en k€
    %td= number_with_precision(@projet.resumes[-1].cout, options = {delimiter: ' ', presicion: 0}) if not @projet.resumes.empty?
  %tr
    %td.bold Dérive coût
    %td= number_to_percentage(@projet.derive_cout,options = {precision: 0}) if @projet.derive_cout
  %tr
    %td.bold Durée en années
    %td= number_with_precision(@projet.resumes[-1].duree, options = {precision: 1}) if not @projet.resumes.empty?
  %tr
    %td.bold Dérive durée
    %td= number_to_percentage(@projet.derive_duree,options = {precision: 0}) if @projet.derive_duree

- if not @projet.resumes.empty? then

  %h2 Historique des études Mareva publiées

  %table
    %tr
      %th Id
      %th Date
      %th Stade
      %th Coût
      %th Durée
      %th Note

    - @projet.resumes.each do |resume|
      %tr
        %td= resume.etude_id
        %td= resume.date
        %td= resume.stade
        %td= number_with_precision(resume.cout, options = {delimiter: " ", precision: 0})
        %td= number_with_precision(resume.duree, options = {precision: 1})
        %td= number_with_precision(resume.note, options = {precision: 1})
%br
= link_to 'Toutes les études', projet_etudes_path(@projet)
\|
= link_to 'Modif', edit_projet_path(@projet)
\|
= link_to 'Retour à la liste', projets_path