config/routes.rb
Valeur::Application.routes.draw do
  
  devise_for :utilisateurs

  resources :strategies, only: [:show, :edit, :update]

  resources :rentabilites, only: [:show]

  resources :directs, only: [:show, :edit, :update]

  resources :indirects, only: [:show, :edit, :update]

  resources :fonctions, only: [:show, :edit, :update]

  resources :gains, only: [:show, :edit, :update]

#  resources :detail, only: [:show]

  resources :parametrages


  resources :projets do
    resources :etudes
  end

  # map '/' to be a redirect to '/projets'

match "/" => redirect("/projets")
match '/aide_projets', :to => redirect('/aide_projets.html')

end

app/controllers/directs_controller.rb
# -*- coding: utf-8 -*-
require 'mareva'
require 'autofocus'

class DirectsController < ApplicationController

include Autofocus

  # GET /directs/1
  # GET /directs/1.json
  def show
    @etude = Etude.find(params[:id])
    @etude.lit_rentabilite
    @modif = Etude.modif_supp_apparents([@etude])[@etude._id][:modif]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @etude }
    end
  end

  # GET /directs/1/edit
  def edit
    @etude = Etude.find(params[:id])
    @direct = @etude.lit_direct_indirect('direct')
  end

  # PUT /directs/1
  # PUT /directs/1.json
  def update
    @etude = Etude.find(params[:id])
    respond_to do |format|
      @auto = autofocus(params,@etude.etude_rentabilite.direct.details.count,0)
      if @etude.etude_rentabilite.direct.update_attributes(params[:direct])
        if params[:commit] then
          @etude.etude_rentabilite.a_calculer = true
          @etude.simplifie_direct
          flash[:notice] = "Les coûts directs ont bien été mis à jour."
          if params[:commit].capitalize == 'Actualiser' then
            @direct = @etude.lit_direct_indirect('direct')
            format.html { render action: "edit"}
            format.json { head :no_content }
          else
            @modif = Etude.modif_supp_apparents([@etude])[@etude._id][:modif]
            format.html { render action: "show"}
            format.json { head :no_content }
          end
        else
          @direct = @etude.traite_touche(params)
          format.html { render action: "edit" }
          format.json { head :no_content }
        end
      else
        flash[:notice] = "Problème de mise à jour des coûts directs."
        format.html { render action: "edit", notice: '' }
        format.json { render json: @projet.errors }
      end
    end
  end
end

app/views/directs/edit.html.haml
%p#notice= notice

%h2 Saisie/modification des coûts directs d'investissement de l'étude  #{@etude._id} du projet #{@etude.projet.nom}
= form_for @direct, :url => direct_path(@etude) do |dir_form|
  %header
    = dir_form.submit 'Actualiser', :autofocus => @auto == 'Actualiser'
    \
    = dir_form.submit 'Enregistrer'
  %article#detail
    %table#detail
      %tr
        %th.touche{:colspan => 3} Actions
        %th.description Description du coût
        %th.nature Nature
        %th.totaux --Totaux--
        - @etude.liste_annees.each do |annee|
          %th.annee=annee
      -i=1
      -@direct.details.each do |detail|
        = dir_form.fields_for :details,detail do |detail_form|
          %tr{:id => [i]}
            %td= dir_form.submit 'Sup', :class => 'action', :name => "s#{i}"
            %td= dir_form.submit 'Ins^', :class => 'action', :name => "h#{i}"
            %td= dir_form.submit 'Insv', :class => 'action', :name => "b#{i}"
            %td.description= detail_form.text_area :description,:autofocus => @auto == i.to_s,:cols => 54,:rows => 1
            %td.nature= detail_form.select :nature,Etude.liste_natures[Direct].keys,include_blank: true,:size => 4
            %td.totaux.montant= number_with_precision(detail.total, options =  {delimiter: " ", precision: 1}) unless detail.total == 0
            -detail.montants.each do |montant|
              = detail_form.fields_for :montants,montant do |montant_form|
                %td.montant= montant_form.number_field :montant,:value => number_with_precision(montant.montant,options={precision: 1}), :size => 1
          -i+=1
      %tr.totaux
        %td.touche
        %td.touche
        %td.touche
        %td.description= @direct.calculees[0].description
        %td
        %td.montant=number_with_precision(@direct.total, options =  {delimiter: " ", precision: 1}) unless @direct.total == nil || @direct.total == 0
        -@direct.calculees[0].montants.each do |montant|
          %td.montant= number_with_precision(montant.montant, options =  {delimiter: " ", precision: 1}) unless montant.montant == 0

  %table#cadre_com_direct
    %td#somme
      %article#somme
        %table#somme
          %tr
            %th.nature Coûts directs pluriannuels 
            %th.montant Totaux (k€)
          - @etude.etude_rentabilite.direct.sommes.each do |somme|
            %tr
              %td.nature= somme.nature
              %td.montant= number_with_precision(somme.valeur, options = {delimiter: " ", precision: 1}) unless somme.valeur == 0
    %th#commentaire_direct
      %article#commentaire
        =dir_form.label :commentaires, :class => "commentaire"
        =dir_form.text_area :commentaires, :cols => 80, :rows => 6
  %footer
    = dir_form.submit 'actualiser', :autofocus => @auto == 'actualiser'
    \
    = dir_form.submit 'enregistrer'

app/views/directs/show.html.haml
%p#notice= notice

%h2 Coûts directs d'investissement de l'étude  #{@etude._id} du projet #{@etude.projet.nom}
%header
  -if @modif
    = link_to 'Modif', edit_direct_path(@etude)
    \|
  = link_to 'Rentabilité', rentabilite_path(@etude)
  \|
  = link_to 'Etude', projet_etude_path(@etude.projet, @etude)
%article#detail
  %table#detail
    %th.description Description du coût
    %th.nature Nature
    =render :partial=>"partages/ligne_annees",:object=>@etude.etude_rentabilite.direct.calculees[0].montants,:locals=>{:annees=>@etude.liste_annees}
    -@etude.etude_rentabilite.direct.details.each do |det|
      %tr
        %td.description= det.description
        %td.nature=det.nature
        =render :partial => "partages/ligne", :object => det, :locals => { :annees => @etude.liste_annees , :signe => '+' }

    %tr.totaux
      %td.description= @etude.etude_rentabilite.direct.calculees[0].description
      %td
      =render :partial=>"partages/ligne",:object=>@etude.etude_rentabilite.direct.calculees[0],:locals=>{:annees=>@etude.liste_annees,:signe=>'+'}

%table#cadre_com_direct
  %td#somme
    %article#somme
      %table#somme
        %tr
          %th.nature Coûts directs pluriannuels 
          %th.montant Totaux (k€)
        - @etude.etude_rentabilite.direct.sommes.each do |somme|
          %tr
            %td.nature= somme.nature
            %td.montant= number_with_precision(somme.valeur, options = {delimiter: " ", precision: 0}) unless somme.valeur == 0
  %th#commentaire_direct
    %article#commentaire
      Commentaires :
      =@etude.etude_rentabilite.direct.commentaires
%footer
  -if @modif
    = link_to 'Modif', edit_direct_path(@etude)
    \|
  = link_to 'Rentabilité', rentabilite_path(@etude)
  \|
  = link_to 'Etude', projet_etude_path(@etude.projet, @etude)