config/routes.rb
Valeur::Application.routes.draw do
  
  devise_for :utilisateurs

  resources :strategies, only: [:show, :edit, :update]

  resources :rentabilites, only: [:show]

  resources :directs, only: [:show, :edit, :update]

  resources :indirects, only: [:show, :edit, :update]

  resources :fonctions, only: [:show, :edit, :update]

  resources :gains, only: [:show, :edit, :update]

#  resources :detail, only: [:show]

  resources :parametrages


  resources :projets do
    resources :etudes
  end

  # map '/' to be a redirect to '/projets'

match "/" => redirect("/projets")
match '/aide_projets', :to => redirect('/aide_projets.html')

end

app/models/etude.rb
# encoding: utf-8 
require 'coherence_projet'
require 'mareva'
require 'irr'

#
# la structure des champs option, appreciation et ponderation est voisine
# la clé est le texte qui apparait en choix à l'utilisateur
# la valeur est le coefficient de pondération pour le champ ponderation
#               la note seuil pour le champ appreciation
#               la note pour l'option
# pour les champs pondération et option, le couple "choisissez une option",nil est présent
# 


class Etude

  def self.copie(objet,parent)
    la_copie = objet.class.new
    if objet._parent then
      nom_parent = nil
      objet.associations.each do |assoc|
        if assoc[1][:relation] == Mongoid::Relations::Embedded::In then
          nom_parent = assoc[0]
          break
        end
      end
      la_copie.send nom_parent+'=',parent if nom_parent
    end
    objet.fields.each do |champ|
      la_copie[champ[0]] = objet[champ[0]] unless champ[0] == '_id'
    end
    if la_copie.class == Etude then
      la_copie.code = 'Copie de ' + la_copie.code + ' (' + Time.now.tv_sec.to_s + ')'
      la_copie.publie = false
      la_copie.date_publication = nil
    end
    la_copie.save # ajouter avant la référence à l'objet père
    objet.associations.each do |assoc|
      if assoc[1][:relation] == Mongoid::Relations::Embedded::One && objet[assoc[0]]
        la_copie.send assoc[0]+'=', Etude.copie((objet.send assoc[0]),la_copie)
      elsif assoc[1][:relation] == Mongoid::Relations::Embedded::Many && objet[assoc[0]]
        (objet.send assoc[0]).each do |element|
          Etude.copie(element,la_copie)
        end
      end
    end
    la_copie
  end

  def insere_detail(ins,objet)
    m = /^(.)(\D*)(\d+)/.match(ins)
    if m[1] == 'h' then dec = 1 else dec = 0 end
    if m[2] == 'actuelle'
      obj = objet.situations[0]
    elsif m[2] == 'cible' then
      obj = objet.situations[1]
    else
      obj = objet
    end
    i = m[3].to_i - dec
    j = obj.details.count
    obj.details << Detail.new
    self.liste_annees.each { |annee| obj.details[-1].montants << Montant.new(annee: annee) }
    while j != i
      obj.details[j].description,obj.details[j-1].description = obj.details[j-1].description,obj.details[j].description
      obj.details[j].nature,obj.details[j-1].nature = obj.details[j-1].nature,obj.details[j].nature
      obj.details[j].unite,obj.details[j-1].unite = obj.details[j-1].unite,obj.details[j].unite
      obj.details[j].total,obj.details[j-1].total = obj.details[j-1].total,obj.details[j].total
      self.liste_annees.each_index do |ind|
        obj.details[j].montants[ind].montant,obj.details[j-1].montants[ind].montant = \
          obj.details[j-1].montants[ind].montant,obj.details[j].montants[ind].montant
      end
      j -= 1
    end
    objet.save
    objet
  end

  def supprime_detail(sup,objet)
    m = /^(.)(\D*)(\d+)/.match(sup)
    if m[2] == 'actuelle' then
      obj = objet.situations[0]
    elsif m[2] == 'cible' then
      obj = objet.situations[1]
    else
      obj = objet
    end
    i = m[3].to_i - 1
    obj.details.delete(obj.details[i])
    objet
  end

  def traite_touche(params)
    if params[:indirect] then 
      objet = self.etude_rentabilite.indirect
    elsif params[:direct] then
      objet = self.etude_rentabilite.direct
    elsif params[:fonction] then
      objet = self.etude_rentabilite.fonction
    else
      objet = self.etude_rentabilite.gain
    end
    ins = params.key('Ins^')
    return self.insere_detail(ins,objet) if ins
    ins = params.key('Insv')
    return self.insere_detail(ins,objet) if ins
    return self.supprime_detail(params.key('Sup'),objet)
  end

  def somme_pourcent(params)
    total = 0
    params[:repartitions_attributes].each do |repart|
      total += repart[1][:pourcent].to_i
    end
    params[:somme_pourcent] = total.to_s
    params
  end

 def self.finalise_calculs(objet,index)
    objet.calculees.each do |calculee|
      calculee.total = 0
      calculee.montants.each { |mt| calculee.total += mt.montant }
      calculee.montants.where(montant: 0).destroy_all
      calculee.montants.where(montant: nil).destroy_all
    end
    objet.total = objet.calculees[index].total
    true
  end

  def simplifie_fonction
    self.etude_rentabilite.fonction.situations.each do |situation|
      totaux = self.reduction_details(situation)
      if totaux[:unite_annee][:ETP] != 0 then
        self.calcul_cout_moyen(situation.repartitions, situation.calculees[0], totaux[:unite_annee][:ETP], situation.calculees[1], situation.calculees[2])
      end
      Etude.cout_mo_total(situation.calculees[3],totaux[:unite_annee][:k€])
      situation.calculees[2].montants.each_index do |i|
        situation.calculees[4].montants[i].montant = situation.calculees[2].montants[i].montant + \
                                                     situation.calculees[3].montants[i].montant
      end
    end
    self.etude_rentabilite.fonction.situations[0].calculees[4].montants.each_index do |i|
      self.etude_rentabilite.fonction.calculees[0].montants[i].montant = self.etude_rentabilite.fonction.situations[1].calculees[4].montants[i].montant - \
                                                                         self.etude_rentabilite.fonction.situations[0].calculees[4].montants[i].montant
    end
    self.etude_rentabilite.fonction.situations.each { |situation| Etude.finalise_calculs(situation,4) }
    Etude.finalise_calculs(self.etude_rentabilite.fonction,0)
    self.etude_rentabilite.save
  end

  def reduction_details(objet)
    totaux_nature = Hash.new(0)
    totaux_nature_unite_annee = Hash.new(0)
    totaux_unite_annee = Hash.new (0)
    objet.details.where(description: "").destroy_all
    objet.details.where(nature: "").destroy_all
    objet.details.each do |detail|
      if objet.class == Gain
        detail.unite = 'k€' if detail.unite == :''
      else
        detail.unite = Etude.liste_natures[objet.class][detail.nature]
      end
      totaux_unite_annee[detail.unite] = Hash.new(0) if not totaux_unite_annee.has_key?(detail.unite)
      totaux_nature_unite_annee[detail.nature] = Hash.new(0) if not totaux_nature_unite_annee.has_key?(detail.nature)
      totaux_nature_unite_annee[detail.nature][detail.unite] = Hash.new(0) if not totaux_nature_unite_annee[detail.nature].has_key?(detail.unite)
      detail.total = 0
      detail.montants.where(montant: 0).destroy_all
      detail.montants.where(montant: nil).destroy_all
      detail.montants.each do |mt|
        detail.total += mt.montant
        totaux_unite_annee[detail.unite][mt.annee] += mt.montant
        totaux_nature_unite_annee[detail.nature][detail.unite][mt.annee] += mt.montant
      end
      totaux_nature[detail.nature] += detail.total
    end
    {:nature => totaux_nature, :unite_annee => totaux_unite_annee, :nature_unite_annee => totaux_nature_unite_annee}
  end

  def self.cout_mo_total(calculee,totaux€)
    if totaux€ != 0
      calculee.montants.each do |mt|
        mt.montant = totaux€[mt.annee]
      end
    else
      calculee.montants.each do |mt|
        mt.montant = 0
      end
    end
    true
  end

  def calcule_cout_moyen_unitaire(totaux_unite_annee,repartitions,calculee)
    calculee.montants.each_index do |i_mt|
      mt = calculee.montants[i_mt]
      if totaux_unite_annee[mt.annee] != 0 then
        cout_moyen = 0
        repartitions.each do |repart|
          if repart.pourcent && repart.pourcent != 0
            cadre = self.etude_rentabilite.cadres.where(cadre: repart.cadre).first
            cout_moyen += repart.pourcent * cadre.cout_annuels.where(:annee => mt.annee.match(/(\d+)/)[1]).first.montant
          end
        end
        calculee.montants[i_mt].montant = cout_moyen/100
      else
        calculee.montants[i_mt].montant = 0
      end
    end
    true            
  end

  def calcul_cout_moyen(repartitions, calculee_nb, totaux_unite_annee, calculee_un, calculee_ts)
    calculee_nb.montants.each { |mt| mt.montant = totaux_unite_annee[mt.annee] }
    self.calcule_cout_moyen_unitaire(totaux_unite_annee,repartitions,calculee_un) unless totaux_unite_annee == 0
    calculee_nb.montants.each_index do |i|
      if calculee_nb.montants[i].montant != 0
        calculee_ts.montants[i].montant = calculee_nb.montants[i].montant * \
                                          calculee_un.montants[i].montant
      else
        calculee_ts.montants[i].montant = 0
      end
    end
    true
  end

  def simplifie_gain
    totaux = self.reduction_details(self.etude_rentabilite.gain)
    self.etude_rentabilite.gain.etp_reparts.each_index do |index|
      cle = self.etude_rentabilite.gain.etp_reparts[index].titre.to_sym
      if totaux[:unite_annee][cle] != 0 then
        self.etude_rentabilite.gain.calculees[index].affiche = true
        self.calcule_cout_moyen_unitaire(totaux[:unite_annee][cle],self.etude_rentabilite.gain.etp_reparts[index].repartitions,\
                                         self.etude_rentabilite.gain.calculees[index])
      else
        self.etude_rentabilite.gain.calculees[index].affiche = false
        self.etude_rentabilite.gain.calculees[index].montants.each { |mt| mt.montant = 0 }
      end
    end
    Etude.liste_familles_gain.each_index do |index|
      famille = Etude.liste_familles_gain[index]
      self.etude_rentabilite.gain.calculees[index+5].montants.each { |mt| mt.montant = 0}
      if totaux[:nature_unite_annee][famille] != 0
        totaux[:nature_unite_annee][famille].each_pair do |unite,annees|
          if unite == :k€ then
            self.etude_rentabilite.gain.calculees[index+5].montants.each do |mt|
              mt.montant += annees[mt.annee]
            end
          elsif m=/^ETP(\d+)/.match(unite)
            self.etude_rentabilite.gain.calculees[index+5].montants.each_index do |i|
              annee = self.etude_rentabilite.gain.calculees[index+5].montants[i].annee

app/controllers/etudes_controller.rb
# -*- coding: utf-8 -*-
class EtudesController < ApplicationController

  before_filter :charge_projet

  # GET /etudes
  # GET /etudes.json
  def index
    @etudes = @projet.etudes.all.sort(_id: -1)
    @modif_supp = Etude.modif_supp_apparents(@etudes)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @etudes }
    end
  end

  # GET /etudes/1
  # GET /etudes/1.json
  def show
    @etude = @projet.etudes.find(params[:id])
    @modif_supp = Etude.modif_supp_apparents([@etude])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @etude }
    end
  end

  # GET /etudes/new
  # GET /etudes/new.json
  def new
    @etude = @projet.etudes.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @etude }
    end
  end

  # GET /etudes/1/edit
  def edit
    @etude = @projet.etudes.find(params[:id])
    @etude = Etude.copie(@etude,@etude.projet) if params[:copie]=='oui'
    @inactif = @etude.inactif

  end

  # POST /etudes
  # POST /etudes.json
  def create
    @etude = @projet.etudes.new(params[:etude])

    respond_to do |format|
      if @etude.save
        format.html { redirect_to [@projet, @etude], notice: "L'étude a été créée." }
        format.json { render json: @etude, status: :created, location: @etude }
      else
        format.html { render action: "new" }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /etudes/1
  # PUT /etudes/1.json
  def update
    @etude = @projet.etudes.find(params[:id])

    respond_to do |format|
      if @etude.update_attributes(params[:etude])
        @etude.gere_resumes
        format.html { redirect_to [@projet, @etude], notice: "L'étude a bien été mise à jour." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etudes/1
  # DELETE /etudes/1.json
  def destroy
    @etude = @projet.etudes.find(params[:id])
    @etude.destroy

    respond_to do |format|
      format.html { redirect_to projet_etudes_path(@projet) }
      format.json { head :no_content }
    end
  end
  private
    def charge_projet
      @projet = Projet.find(params[:projet_id])
    end
end

app/helpers/etudes_helper.rb
module EtudesHelper
end

app/views/etudes/_form.html.haml
= form_for ([@projet, @etude]) do |f|
  - if @etude.errors.any?
    #error_explanation
      %h2= "#{pluralize(@etude.errors.count, "error")} : cette étude n'a pas pu être enregistrée"
      %ul
        - @etude.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :code
    = f.text_field :code, :disabled => ["partiel","total"].include?(@inactif)
  .field
    = f.label :stade
    = f.select :stade, @etude.liste_stades, :disabled => ["partiel","total"].include?(@inactif)
  .field
    = f.label :description
    = f.text_field :description, :disabled => ["partiel","total"].include?(@inactif)
  .field
    = f.label :date_debut, 'Date début'
    = f.date_select :date_debut, :disabled => ["partiel","total"].include?(@inactif)
  .field
    = f.label :duree_projet, 'Durée du projet'
    = f.text_field :duree_projet, :disabled => ["partiel","total"].include?(@inactif)
  .field
    = f.label :type_produit
    = f.select :type_produit, @etude.liste_types_produit, :disabled => if ["partiel","total"].include?(@inactif) then @etude.liste_types_produit else [] end
  .field
    = f.label :duree_vie, 'Durée de vie'
    = f.number_field :duree_vie, :disabled => ["partiel","total"].include?(@inactif)
  .field
    = f.label :taux_actu, "Taux d'actualisation (%)"
    = f.number_field :taux_actu, :disabled => ["partiel","total"].include?(@inactif)
  - if params["action"] != "new" then
    .field
      = f.label :publie, 'Publié'
      = f.check_box :publie, :disabled => ["total"].include?(@inactif)
    .field
      = f.label :date_publication, 'Date publication'
      = f.date_select :date_publication, :disabled => ["partiel","total"].include?(@inactif)
    .field
      = f.label :cout, 'Coût'
      = f.text_field :cout, :disabled => ["partiel","total"].include?(@inactif)
        
    .field
      = f.label :delai_retour, 'Délai retour'
      = f.text_field :delai_retour, :disabled => ["partiel","total"].include?(@inactif)
    .field
      = f.label :note
      = f.text_field :note, :disabled => ["partiel","total"].include?(@inactif)

  .actions
    = f.submit 'Enregistrer'

app/views/etudes/edit.html.haml
%h2 Modification de l'étude #{@etude._id} du projet #{@projet.nom}

= render 'form'

= link_to 'Détail', projet_etude_path(@projet, @etude) 
\|
= link_to 'Retour à la liste', projet_etudes_path(@projet)

app/views/etudes/index.html.haml
%h2 Liste des études du projet #{@projet.nom}


- if not @etudes.empty? then

  %table#etudes
    %tr
      %th Id
      %th Code
      %th Stade
      %th Publié
      %th Le
      %th Date début
      %th Durée
      %th Coût
      %th Retour
      %th Note
      %th.rien
      %th.rien
      %th.rien

    - @etudes.each do |etude|
      %tr
        %td.droit= etude._id
        %td= etude.code
        %td= etude.stade
        %td.centre= "#{if etude.publie then "Oui" else "Non" end}"
        %td.centre= etude.date_publication
        %td.centre= etude.date_debut
        %td.droit= number_with_precision(etude.duree_projet, options = {precision: 1}) 
        %td.droit= number_with_precision(etude.cout, options = {delimiter: " ", precision: 0}) unless etude.cout == nil
        %td.droit= number_with_precision(etude.delai_retour, options = {precision: 1}) unless etude.delai_retour == nil
        %td.droit= number_with_precision(etude.note, options = {precision: 1}) unless etude.note == nil
        %td.centre= link_to 'Détail', projet_etude_path(@projet, etude) 
        %td.centre= link_to 'Copie', edit_projet_etude_path(@projet, etude,:copie=>'oui')
        %td.centre= if @modif_supp[etude._id][:modif] then link_to 'Modif', edit_projet_etude_path(@projet, etude,:copie=>'non') end
        %td.centre= if @modif_supp[etude._id][:supp] then link_to 'Supp', [@projet, etude], confirm: 'Poursuivre la suppression définitive ?', method: :delete end

%br

= link_to 'Nouvelle étude', new_projet_etude_path(@projet)
= link_to 'Liste des projets', projets_path

app/views/etudes/new.html.haml
%h2 Nouvelle étude pour le projet #{@projet.nom}

= render 'form'

= link_to 'Back', projet_etudes_path

app/views/etudes/show.html.haml
%h2 Détail de l'étude #{@etude._id} du projet #{@projet.nom}

%p#notice= notice

%table
  %tr
    %td.bold Code
    %td= @etude.code
  %tr
    %td.bold Stade
    %td= @etude.stade
  %tr
    %td.bold Description
    %td= @etude.description
  %tr
    %td.bold Date début
    %td= @etude.date_debut
  %tr
    %td.bold Durée projet
    %td= number_with_precision(@etude.duree_projet, options = {precision: 1})
  %tr
    %td.bold Type de produit
    %td= @etude.type_produit
  %tr
    %td.bold Durée de vie
    %td= @etude.duree_vie
  %tr
    %td.bold Durée de vie totale
    %td= number_with_precision(@etude.duree_vie_totale, options = {precision: 1})
  %tr
    %td.bold Taux d'actualisation
    %td= number_to_percentage(@etude.taux_actu,:precision => 1) 
  %tr
    %td.bold Publié
    %td= if @etude.publie then "Oui" else "Non" end
  %tr
    %td.bold Date de publication
    %td= @etude.date_publication
  %tr
    %td.bold Coût en k€
    %td= number_with_precision(@etude.cout, options = {delimiter: " ", precision: 0}) unless @etude.cout == nil
  %tr
    %td.bold Délai de retour
    %td= number_with_precision(@etude.delai_retour, options = {precision: 1}) unless @etude.delai_retour == nil
  %tr
    %td.bold Note
    %td= number_with_precision(@etude.note, options = {precision: 1}) unless @etude.note == nil

= if @modif_supp[@etude._id][:modif] then link_to 'Modif', edit_projet_etude_path(@projet, @etude) end
\|
= link_to 'Liste des études', projet_etudes_path(@projet)
\|
= link_to 'Stratégie', strategy_path(@etude)
\|
= link_to 'Rentabilité', rentabilite_path(@etude)