config/routes.rb
Valeur::Application.routes.draw do
  
  devise_for :utilisateurs

  resources :strategies, only: [:show, :edit, :update]

  resources :rentabilites, only: [:show]

  resources :directs, only: [:show, :edit, :update]

  resources :indirects, only: [:show, :edit, :update]

  resources :fonctions, only: [:show, :edit, :update]

  resources :gains, only: [:show, :edit, :update]

#  resources :detail, only: [:show]

  resources :parametrages


  resources :projets do
    resources :etudes
  end

  # map '/' to be a redirect to '/projets'

match "/" => redirect("/projets")
match '/aide_projets', :to => redirect('/aide_projets.html')

end

app/controllers/rentabilites_controller.rb
# -*- coding: utf-8 -*-
require 'mareva'

class RentabilitesController < ApplicationController
  # GET /rentabilites/1
  # GET /rentabilites/1.json
  def show
    @etude = Etude.find(params[:id])
    @rentabilite = @etude.lit_rentabilite
    @rentabilite = @etude.calcule_rentabilite if @rentabilite.a_calculer
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @etude }
    end
  end
end

app/views/rentabilites/_ligne.html.haml
-if ligne
  -montant = ligne.total if signe == '+'
  -montant = -ligne.total if signe == '-'
  %td.totaux=number_with_precision(montant, options = {delimiter: " ",precision: 0}) if montant != 0
  -i=0
  -annees.each do |annee|
    -if ligne.montants[i]
      -if ligne.montants[i].annee == annee
        -if ligne.montants[i].montant != 0
          -if signe == '-'
            %td.montant=number_with_precision(-ligne.montants[i].montant, options = {delimiter: " ",precision: 0})
          -else
            %td.montant=number_with_precision(ligne.montants[i].montant, options = {delimiter: " ",precision: 0})
        -else
          %td.montant
        -i+=1
      -else
        %td.montant
    -else
      -break

app/views/rentabilites/show.html.haml
%p#notice= notice

%h2 Détail du volet rentabilité de l'étude  #{@etude._id} du projet #{@etude.projet.nom}

%table#rentabilite
  %tr
    %th.titre{:colspan => 2} Dépenses d'investissements
    %th.titre{:rowspan => 2} Gains métier
    %th.titre{:rowspan => 2} Impacts sur le SI
  %tr
    %th.titre Coûts directs
    %th.titre Coûts indirects
  %tr
    %td#direct= link_to number_with_precision(@rentabilite.direct.total, options = {delimiter: " ", precision: 0}), direct_path(@etude)
    %td#indirect= link_to number_with_precision(@rentabilite.indirect.total, options = {delimiter: " ",precision: 0}), indirect_path(@etude)
    %td#gain= link_to number_with_precision(@rentabilite.gain.total, option = {delimiter: " ",precision: 0}), gain_path(@etude)
    %td#fonction= link_to number_with_precision(@rentabilite.fonction.total, options = {delimiter: " ",precision: 0}), fonction_path(@etude)
%h3 Rappel des paramètres du projet
%dl
  %dt="Taux d'actualisation"
  %dd="#{number_with_precision(@etude.taux_actu, options = {precision: 1})} %"
  %dt="Durée de vie totale"
  %dd="#{number_with_precision(@etude.duree_vie_totale, options = {precision: 1})} ans"
%article#synthese
  %table#synthese
    %caption Tableau des flux annuels
    %tr#titres
      %th.description
      =render :partial=>"partages/ligne_annees",:object=>@rentabilite.calculees[6].montants,:locals=>{:annees=>@etude.liste_annees}

    %tr#l_0
      -if @rentabilite.direct && @rentabilite.direct.calculees[0]
        %td.description=@rentabilite.direct.calculees[0].description
        =render :partial => "partages/ligne", :object => @rentabilite.direct.calculees[0], :locals => { :annees => @etude.liste_annees , :signe => '-' }
    %tr#l_1
      -if @rentabilite.indirect && @rentabilite.indirect.calculees[4]
        %td.description=@rentabilite.indirect.calculees[4].description
        =render :partial => "partages/ligne", :object => @rentabilite.indirect.calculees[4], :locals => { :annees => @etude.liste_annees, :signe => '-' }
    %tr#l_2
      %td.description=@rentabilite.calculees[0].description
      =render :partial => "partages/ligne", :object => @rentabilite.calculees[0], :locals => { :annees => @etude.liste_annees, :signe => '+' }
    %tr#l_3
      %td.description=@rentabilite.calculees[1].description
      =render :partial => "partages/ligne", :object => @rentabilite.calculees[1], :locals => { :annees => @etude.liste_annees, :signe => '+' }
    -if @rentabilite.gain
      -(5..12).each do |rang|
        -if @rentabilite.gain.calculees[rang].montants.count != 0
          %tr{:id => ["l_#{rang-1}"]}
            %td.description=@rentabilite.gain.calculees[rang].description
            =render :partial => "partages/ligne", :object => @rentabilite.gain.calculees[rang], :locals => { :annees => @etude.liste_annees, :signe => '+' }
    %tr#l_12
      %td.description=@rentabilite.gain.calculees[13].description
      =render :partial => "partages/ligne", :object => @rentabilite.gain.calculees[13], :locals => { :annees => @etude.liste_annees, :signe => '+' }
    %tr#l_13
      %td.description=@rentabilite.calculees[2].description
      =render :partial => "partages/ligne", :object => @rentabilite.calculees[2], :locals => { :annees => @etude.liste_annees, :signe => '+' }
    %tr#l_14
      %td.description=@rentabilite.fonction.situations[0].calculees[4].description
      =render :partial=>"partages/ligne",:object=>@rentabilite.fonction.situations[0].calculees[4],:locals=>{:annees=>@etude.liste_annees,:signe=>'+'}
    %tr#l_14
      %td.description=@rentabilite.fonction.situations[1].calculees[4].description
      =render :partial=>"partages/ligne",:object=>@rentabilite.fonction.situations[1].calculees[4],:locals=>{:annees=>@etude.liste_annees,:signe=>'-'}
    %tr#l_15
      %td.description=@rentabilite.fonction.calculees[0].description
      =render :partial=>"partages/ligne",:object=>@rentabilite.fonction.calculees[0],:locals=>{:annees=>@etude.liste_annees,:signe=>'-'}
    -(16..20).each do |rang|
      %tr{:id => ["l_#{rang}"]}
        %td.description=@rentabilite.calculees[rang-13].description
        =render :partial=>"partages/ligne",:object=>@rentabilite.calculees[rang-13],:locals=>{:annees=>@etude.liste_annees,:signe=>'+'}
%h3 Indicateurs de rentabilité
%dl
  %dt="Valeur actualisée nette (VAN)"
  %dd="#{number_with_precision(@etude.van,options = {delimiter: " ",precision: 1})} k€"
  %dt="Taux de rendement interne (TRI)"
  %dd="#{number_with_precision(@etude.tri,options = {precision: 1})} %"
  %dt="Délai de retour"
  %dd="#{number_with_precision(@etude.delai_retour,options = {precision: 1})} ans"
  %dt="Coût total du projet"
  %dd="#{number_with_precision(@etude.cout,options = {delimiter: " ",precision: 1})} k€"
%br
%div#centre=image_tag(@etude.etude_rentabilite.graphe_flux_cumules, alt: 'Graphe des flux cumulés') if @etude.etude_rentabilite.graphe_flux_cumules != ''
%br


= link_to 'Retour étude', projet_etude_path(@etude.projet, @etude)